import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "STOOK Aide",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <link
          rel="icon"
          href="/icon.svg"
          type="image/svg"
          sizes="16x16"
        />
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
